version: 2
jobs:
  test:
    docker:
      - image: circleci/node:9.2.0
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Testing
          command: docker-compose -f docker-compose-test.yml run docker-cicd
  deploy:
    docker:
      - image: circleci/node:9.2.0
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run:
          name: Install EB Command Line
          command: >
            sudo apt-get update &&
            sudo apt-get install -y python python-dev python-pip python-virtualenv &&
            sudo rm -rf /var/lib/apt/lists/* &&
            sudo pip install awsebcli &&
            sudo pip install --upgrade --user awsebcli
      - run: eb --version
      - run: eb init 
      - deploy:
          name: Deploy To ENV Staging
          command: sudo eb deploy docker-cicd-dev

workflows: 
  version: 2 
  docker-cicd: 
    jobs: 
      - deploy